### PR TITLE
only use setTimeout when using phantomjs environment

### PR DESCRIPTION
**Pull request by forberg**

### CODE REVIEW

**Comment by forberg** [comment]
Does this look OK to you? :-)

**Comment by sveisvei** [comment]
Although the comment notes about phantomjs, it might be more browsers who have issues without the timeout. I need to test before commiting to this.

Whats the main issue btw?

**Comment by gregersrygg** [comment]
This looks like a new feature than something for phantomjs. Can you please provide a description?

**Comment by forberg** [comment]
Commited a bit too much :-) I'll fix a new one.

**Pull request closed without merging**
